### ISSUE TITLE
unable to flash firmware

### ISSUE THREAD

**Issue by johannesz-codes** [Xinyuan-LilyGO/T-Encoder-shield#3]
I have trouble flashing new firmware to the shield.
I open the tool for the CH552 and it gets detected. The Arduino IDE tries to flash the board, but the verification fails with the message: packet 0 doesn't match. 
The settings all match the setting described in the image.

Also, the board definitely changed its behavior as the LEDs do not flash as before, but it also does not seem to do what I tell it to do. I tried flashing the examples.

**Comment by LilyGO** [comment]
I also noticed that after programming with Arduino, it cannot be uploaded directly to CH552. The current solution is to find the .bin file generated by Arduino to upload via WCHTOOL. After uploading, you need to turn the switch to the left (run the user code).

**Comment by johannesz-codes** [comment]
Thanks, this worked. Probably should be mentioned on the README.

**Comment by jeff-phil** [comment]
FYI, I am able to upload with Arduino just fine.  

Took me a while to find out how, but finally found this statement here: https://github.com/DeqingSun/ch55xduino/issues/79

_"Note you have to upload the sketch quickly after the power cycle, because a new bootloader will timeout after a few seconds."_
